version: '3.8'

services:
  personregistry.api:
    build:
      context: .
      dockerfile: PersonRegistry.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=PersonRegistryApp;User=sa;Password=Your_password123;TrustServerCertificate=True;MultipleActiveResultSets=True"
    networks:
      - appnetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - appnetwork

volumes:
  mssql_data:

networks:
  appnetwork:
